name: Actions Workflow

on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout 
        uses: actions/checkout@v3
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: simple javascript action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Felipe
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
