name: Container
on: push

jobs: 
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: okteto/node:16
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-version
      