name: Container
on: push

jobs: 
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: okteto/node:16
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello slack"
  
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "felipe","address": "bogotá"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users
