name: Matrix

on: pull_request

jobs:
  node-version:
    strategy: 
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] 
        node_version: [8, 12, 14]
        include: 
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: windows-latest
            node_version: 8
          - os: windows-latest
            node_version: 14
    runs-on: ${{ matrix.os }}
    env: 
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node_version }}
      - name: Log node version
        run:  | 
          node -v
          echo $IS_UBUNTU_8
